# Generated by Django 6.0.3 on 2026-04-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('THREAT_LEVEL_RED', 'THREAT_LEVEL_RED'), ('NODE_VALIDATION', 'NODE_VALIDATION'), ('GHOST_PROTOCOL', 'GHOST_PROTOCOL')], default='GHOST_PROTOCOL', max_length=100),
        ),
    ]
